name: Testerino

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: '16.x'
  AZURE_WEBAPP_NAME: slicedtomatoesf23123
  AZURE_WEBAPP_PACKAGE_PATH: "build"                

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
#        npm run test --if-present

    - name: startup command
      run: |
        echo '{ "script": "serve", "env": { "PM2_SERVE_SPA": 'true', "PM2_SERVE_HOMEPAGE": "./index.html" } }' >> build/process.json
        
    - name: Deploy le App!
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_SECRET }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        